dist: xenial
language: cpp
compiler:
- gcc
addons:
  apt:
    sources:
    - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
    - gcc-6
    - g++-6
cache:
  directories:
  - cmake-build-release/
script:
- ./scripts/travis-build-test.sh
